name: longpress_popup
description: A plugin for flutter_map to show a customisable popup Widget when a marker is long pressed. Also provides methods to show/hide popups.
version: 1.5.4
repository: https://github.com/ymrabti/fluttermap_markerpopup

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^1.1.0
  latlong2: ^0.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
